#ifndef _ERROR_CODE_H
#define _ERROR_CODE_H

namespace propagator{
    enum class ErrorCode{

        SUCCESS,

        ERROR_UNDEFINED_SATELLITE_CODE,
        ERROR_ORBIT_DATA_NOT_OBTAINED,
        ERROR_NO_CORRESPONDING_TLE_IN_FILE,
        ERROR_NO_ORBIT_FILE,
        ERROR_AUX_TIME_INFO_OUT_OF_RANGE,

        ERROR_NULL,
        ERROR_UNDEFINED_COMMAND,
        ERROR_UNDEFINED_STATUS,
        ERROR_UNDEFINED_COORDINATE_SYSTEM,
        ERROR_CANNOT_OBTAIN_DE405_DATA,
        ERROR_READ_IERS_FILE_FAILED,
        ERROR_READ_GS_SENSOR_PARAMETER_FILE_FAILED,
        ERROR_READ_SATELLITE_PARAMETER_FILE_FAILED,
        ERROR_READ_POD_DATA_FILE_FAILED,
        ERROR_READ_OP_OPERATOR_PARAMETER_FILE_FAILED,
        ERROR_READ_OD_OPERATOR_PARAMETER_FILE_FAILED,
        ERROR_UNDEFINED_ESTIMATOR,
        ERROR_UNDEFINED_INTEGRATOR,
        ERROR_UNDEFINED_STK_TYPE,
        ERROR_UNDEFINED_MANEUVER_APPLICATION_TO_OP_METHOD,
        ERROR_UNDEFINED_MANEUVER_ESTIMATION_IN_OD_METHOD,
        ERROR_NO_LEAP_SECOND_INFO_IN_IERS_FILE,
        ERROR_NO_EARTH_ORIENTATION_PARAMETER_IN_IERS_FILE,
        ERROR_NO_NUTATION_OFFSET_INFO_IN_IERS_FILE,
        ERROR_INVALID_MATRIX_SIZE,
        ERROR_IN_ODE78,
        ERROR_READ_OPEN_FDS_CONFIG_FILE_FAILED,
        ERROR_FTP_LIB_INIT_FAILED,
        ERROR_FTP_CONNECT_INIT_FAILED,
        ERROR_FTP_OPEN_HOST_FAILED,
        ERROR_CANNOT_RECEIVE_FTP_FILE,
        ERROR_CANNOT_SEND_FTP_FILE,
        ERROR_LESSTHAN_HMIN,
        ERROR_LARGERTHAN_HMAX,
        ERROR_INVALID_TOKEN_IN_GS_SENSOR_PARAMETER,
        ERROR_INVALID_TOKEN_IN_OPERATOR_PARAMETER,
        ERROR_UNDEFINED_MEASUREMENT_DATA_TYPE,
        ERROR_UNDEFINED_MEASUREMENT_DATA_FORMAT,
        ERROR_UNDEFINED_ORBIT_STACK_FILE_FORMAT,
        ERROR_UNDEFINED_ORBIT_PREDICTION_RESULT_FORMAT,
        ERROR_WRITE_DEBUG_FILE_FAILED,
        ERROR_READ_STATION_PARAMETER_FILE_FAILED,
        ERROR_WRITE_STATION_PARAMETER_FILE_FAILED,
        ERROR_READ_ASCII_MEASUREMENT_DATA_FILE_FAILED,
        ERROR_WRITE_ASCII_MEASUREMENT_DATA_FILE_FAILED,
        ERROR_READ_GEOSC_MEASUREMENT_DATA_FILE_FAILED,
        ERROR_WRITE_GEOSC_MEASUREMENT_DATA_FILE_FAILED,
        ERROR_READ_STK_MEASUREMENT_DATA_FILE_FAILED,
        ERROR_WRITE_STK_MEASUREMENT_DATA_FILE_FAILED,


        ERROR_READ_GPS_MEASUREMENT_DATA_FILE_FAILED,
        ERROR_WRITE_GPS_MEASUREMENT_DATA_FILE_FAILED,



        ERROR_READ_SLR_MEASUREMENT_DATA_FILE_FAILED,
        ERROR_WRITE_SLR_MEASUREMENT_DATA_FILE_FAILED,



        ERROR_READ_ORBIT_STACK_DATA_FILE_FAILED,
        ERROR_WRITE_ORBIT_STACK_DATA_FILE_FAILED,
        ERROR_FTP_CONNECT_TARGET_FAILED,
        ERROR_FTP_GET_FILE_FAILED,
        ERROR_FTP_INVALID_TARGET_DIR,
        ERROR_FTP_PUT_FILE_FAILED,
        ERROR_FTP_CREATE_DIRECTORY_FAILED,
        ERROR_READ_OPEN_SIMULATOR_CONFIG_FILE_FAILED,
        ERROR_WRITE_ORBIT_PARAMETER_FILE_FAILED,
        ERROR_READ_ORBIT_PARAMETER_FILE_FAILED,
        ERROR_WRITE_ORBIT_PREDICTION_DATA_FILE_FAILED,
        ERROR_READ_ORBIT_PREDICTION_DATA_FILE_FAILED,
        ERROR_NO_CORRESPONDING_MEASUREMENT_DATA_SAMPLE,
        ERROR_NO_GS_SENSOR_PARAMETER_CORRESPONDING_TO_STATION,
        ERROR_WRITE_OPEN_FDS_CONFIG_FILE_FAILED,
        ERROR_WRITE_GS_SENSOR_PARAMETER_FILE_FAILED,
        ERROR_WRITE_SATELLITE_PARAMETER_FILE_FAILED,
        ERROR_WRITE_OD_OPERATOR_PARAMETER_FILE_FAILED,
        ERROR_WRITE_OP_OPERATOR_PARAMETER_FILE_FAILED,
        ERROR_NOT_ENOUGH_STATION_ID_DEFINED_IN_OPERATOR_PARAMETER,
        ERROR_NOT_ENOUGH_MEASUREMENT_DATA_IN_ESTIMATION_WINDOW,
        ERROR_INVALID_COMPARE_DATA,
        ERROR_WRITE_OP_REPORT_FILE_FAILED,
        ERROR_WRITE_OPEN_OD_REPORT_FILE_FAILED,
        ERROR_WRITE_OPEN_OD_RESIDUAL_FILE_FAILED,
        ERROR_MEMORY_ALLOCATE_IN_COMPARE,
        ERROR_UKF_MEASUREMENT_MATRIX_SIZE_ERROR,
        ERROR_UKF_PROCESSOR_MATRIX_SIZE_ERROR,
        ERROR_NO_CP_FILE,
        ERROR_INVALID_FILE_FORMAT,
        ERROR_CANNOT_WRITE_CP_FILE,
        ERROR_OD_START_TIME_IS_LATER_THAN_END_TIME,
        ERROR_NOT_ENOUGH_ORBIT_SAMPLES_FOR_MEAN_ELEMENT_CALCULATION,
        ERROR_UNDEFINED_FUEL_MASS_SOURCE,


        ERROR_READ_OBSENSOR_PARAMETER_FILE_FAILED,
        ERROR_READ_SKOPERATOR_PARAMETER_FILE_FAILED,
        ERROR_READ_SROPERATOR_PARAMETER_FILE_FAILED,
        ERROR_READ_THRUSTER_PARAMETER_FILE_FAILED,
        ERROR_READ_THRUSTER_OPERATION_DATA_FILE_FAILED,
        ERROR_READ_THRUSTER_STACK_DATA_FILE_FAILED,
        ERROR_READ_THRUSTER_PROFILE_FILE_FAILED,
        ERROR_READ_THRUSTER_CHARACTERISTICS_FILE_FAILED,
        ERROR_READ_WHEEL_OFF_LOADING_MANEUVER_STACK_FILE_FAILED,
        ERROR_READ_EPOPERATOR_PARAMETER_FILE_FAILED,
        ERROR_READ_PVT_TELEMETRY,
        ERROR_READ_TOT_TELEMETRY,
        ERROR_READ_FAOPERATOR_PARAMETER_FILE_FAILED,
        ERROR_READ_MANEUVER_STACK_DATA_FILE_FAILED,
        ERROR_READ_FAPVT_STACK_DATA_FILE_FAILED,
        ERROR_READ_FATOT_STACK_DATA_FILE_FAILED,
        ERROR_READ_SPB_PARAMETER_FILE_FAILED,
        ERROR_READ_WOL_PARAMETER_FILE_FAILED,


        ERROR_READ_IRES_PARAMETER_FILE_FAILED,



        ERROR_WRITE_OBSENSOR_PARAMETER_FILE_FAILED,
        ERROR_WRITE_SKOPERATOR_PARAMETER_FILE_FAILED,
        ERROR_WRITE_SROPERATOR_PARAMETER_FILE_FAILED,
        ERROR_WRITE_THRUSTER_PARAMETER_FILE_FAILED,
        ERROR_WRITE_THRUSTER_OPERATION_DATA_FILE_FAILED,
        ERROR_WRITE_THRUSTER_STACK_DATA_FILE_FAILED,
        ERROR_WRITE_THRUSTER_PROFILE_FILE_FAILED,
        ERROR_WRITE_THRUSTER_CHARACTERISTICS_FILE_FAILED,
        ERROR_WRITE_WHEEL_OFF_LOADING_MANEUVER_STACK_FILE_FAILED,
        ERROR_WRITE_EPOPERATOR_PARAMETER_FILE_FAILED,
        ERROR_WRITE_FAOPERATOR_PARAMETER_FILE_FAILED,
        ERROR_WRITE_MANEUVER_STACK_DATA_FILE_FAILED,
        ERROR_WRITE_FAPVT_STACK_DATA_FILE_FAILED,
        ERROR_WRITE_FATOT_STACK_DATA_FILE_FAILED,
        ERROR_WRITE_WOL_PARAMETER_FILE_FAILED,

        ERROR_INVALID_THRUSTER_PARAMETER_FILE,
        ERROR_INVALID_THRUSTER_SET,
        ERROR_INVALID_THRUSTER_OP_DATA_FORMAT,
        ERROR_INVALID_THRUSTER_STACK_DATA_FORMAT,
        ERROR_INVALID_THRUSTER_PROFILE_FORMAT,
        ERROR_INVALID_THRUSTER_CHARACTERISTICS_TYPE,
        ERROR_INVALID_THRUSTER_CHARACTERISTICS_FORMAT,
        ERROR_INVALID_WHEEL_OFF_LOADING_MANEUVER_STACK_FILE_FORMAT,
        ERROR_NO_THRUSTER_AVAILABLE,
        ERROR_INVALID_MANEUVER_TYPE,

        ERROR_OUTOF_OBSENSOR_DATA,
        ERROR_OUTOF_RANGE_THRUSTER_STACK,
        ERROR_OUTOF_RANGE_THRUSTER_PROFILE,
        ERROR_OUTOF_RANGE_WHEEL_OFF_LOADING_MANEUVER,


        ERROR_WRITE_AM_REPORT_FILE_FAILED,


        ERROR_WRITE_EP_REPORT_FILE_FAILED,
        ERROR_WRITE_SK_REPORT_FILE_FAILED,
        ERROR_WRITE_SR_REPORT_FILE_FAILED,
        ERROR_WRITE_PVTFA_REPORT_FILE_FAILED,
        ERROR_WRITE_TOTFA_REPORT_FILE_FAILED,
        ERROR_WRITE_PVTPT_REPORT_FILE_FAILED,
        ERROR_WRITE_PVTSTACK_REPORT_FILE_FAILED,
        ERROR_WRITE_EPOSL_REPORT_FILE_FAILED,
        ERROR_WRITE_SKOSL_REPORT_FILE_FAILED,


        ERROR_WRITE_SROSL_REPORT_FILE_FAILED,
        ERROR_WRITE_AMOSL_REPORT_FILE_FAILED,
        ERROR_WRITE_UTILOSL_REPORT_FILE_FAILED,


        ERROR_WRITE_SPB_PARAMETER_FILE_FAILED,

        ERROR_WRITE_TLE_FILE_FAILED,


        ERROR_INVALID_SK_ALGORITHM,
        ERROR_INVALID_SR_ALGORITHM,
        ERROR_INVALID_SR_CONSTRAINTS,
        ERROR_INVALID_PVT_TELEMETRY,
        ERROR_INVALID_TOT_TELEMETRY,
        ERROR_INVALID_FA_ALGORITHM,
        ERROR_NULL_VALUE_IN_TOTFA,
        ERROR_COMPUTE_FA_PT_FAILED,
        ERROR_INVALID_TOTFA_TYPE,

        ERROR_EAST_DRIFT_STATION_KEEPING_NOT_SUPPORTED,

        ERROR_READ_SIMULATION_PARAMETER_FILE_FAILED,
        ERROR_WRITE_SIMULATION_PARAMETER_FILE_FAILED,
        ERROR_NO_MEASUREMENT_SIMULATION_PARAMETER_CORRESPONDING_TO_STATION,

        ERROR_NO_CORRESPONDING_TRANSVERSE_ANGULAR_MOMENTUM_DATA,
        ERROR_TOO_SLOW_SUN_ROTATION_RATE,


        ERROR_READ_DATABASE,
        ERROR_WRITE_DATABASE,
        ERROR_CONNECT_DATABASE,
        ERROR_DISCONNECT_DATABASE,
        ERROR_FAILED_DBADAPTER_SETTING,
        ERROR_INVALID_ID,
        ERROR_INVALID_PASSWORD,

        ERROR_EXECUTE_EXTERNAL_PROGRAM,


        ERROR_SUN_POINTING_PERIGEE_TWO_BURNS_FAILED,

        ERROR_UNDEFINED_MODELING_TYPE,
        ERROR_UNDEFINED_ORBIT_PROPAGATION_INPUT_TYPE,
        ERROR_UNDEFINED_ORBIT_PROPAGATOR_TYPE,

        WARNING_BASE,
        WARNING_STATION_KEEPING_NOT_NECESSARY,


        WARNING_PERIOD_OSCILLATOR_UPDATE,
        WARNING_PERIOD_OSCILLATOR_UPDATE_DRIFT,
        WARNING_OSCILLATOR_UPDATE_TIME,


        WARNING_WHEEL_OFFLOADING_PERIOD_CHANGED,
        WARNING_WHEEL_OFFLOADING_PITCH_ANGULAR_MOMENTUM_OUT_OF_RANGE,
        WARNING_WHEEL_OFFLOADING_TRANSVERSE_ANGULAR_MOMENTUM_OUT_OF_RANGE,

        WARNING_SUN_POINTING_PERIGEE_LAG_ANGLE_CALCULATION_FAILED,
        WARNING_SUN_POINTING_PERIGEE_ONE_BURN_FAILED,


        WARNING_SKCPS_PMD_CAPACITY_OVERFLOW,
        WARNING_SKCPS_ONLY_NORTHSOUTH_PREMANEUVER_REQUESTED,
        WARNING_SKCPS_PRESSURES_OUTSIDE_OF_PRESSURE_BOX,

        WARNING_MORE_THAN_3_STATIONS_IN_MEASUREMENT_DATA
    };
}